### ISSUE TITLE
nature_dqn.py代码问题

### ISSUE THREAD

**Issue by wanghaotian233** [ljpzzz/machinelearning#10]
您好，请问在target net网络的代码里，为什么target_Q_value计算用的是h_layer？应该是h_layer_t吧

# hidden layers
h_layer_t = tf.nn.relu(tf.matmul(self.state_input,W1t) + b1t)
# Q Value layer
self.target_Q_value = tf.matmul(h_layer,W2t) + b2t

**Comment by ljpzzz** [comment]
非常感谢指正错误，代码已经更正。
