### ISSUE TITLE
公众号建议

### ISSUE THREAD

**Issue by Lotrea** [ljpzzz/machinelearning#3]
您好，长期阅读您深入浅出的博客文章，获益匪浅。
不知您是否有公众号？方便订阅和日常移动端阅读。
如果没有，小小建议您能开通一个，更大范围地传播您整理的知识精华。

**Comment by zsweet** [comment]
有这方面意向，请问你的身份是？

Weihao Li <notifications@github.com> 于2019年3月27日周三 下午5:10写道：

**Comment by ljpzzz** [comment]
你好，感谢建议。目前一是没有时间维护公众号，二是目前微信的公众号对LaTex公式的支持很不友好。我的文章基本是文字和数学公式混杂，转化成公众号文章所有的公式都得去贴图，不光费力而且贴图后公式阅读体验很差。
因此暂时不考虑。

**Comment by xaxfan** [comment]
如果作者的文章是直接的github上的markdown就完美了，可以fork，然后自己读的时候可以修改成自己的知识
