### ISSUE TITLE
最小二乘法

### ISSUE THREAD

**Issue by xaxfan** [ljpzzz/machinelearning#4]
https://www.cnblogs.com/pinard/p/5976811.html
您好，最小二乘法和损失函数是平方损失有什么区别么，一般平方损失是用梯度下降迭代法求解，最小二乘法是用解析法直接求解，梯度下降法是数值法？

**Comment by ljpzzz** [comment]
你好，损失函数是一个单独的概念，与你使用最小二乘法还是其他的优化方法，比如梯度下降法无关。
对于一个给定的损失函数，比如平方损失。有很多求解极值对应模型参数的方法。比如最小二乘法，这个是解析解。或者是梯度下降法，这个是启发式的方法。
